### ISSUE TITLE
Non-Translated Posts referencing random other translated post

### ISSUE THREAD

**Issue by jcsacto** [shawnhooper/wpml-rest-api#25]
Hi, thanks for building this.  Was trying this out to solve my issue about getting my post data via API where WPML doesn't expose post unless I use the lang parameter.  Trying to get everything all at once rather than combining data sets.  

What I'm seeing unfortunately is when there is not actually a translations for my post, it 'makes one up' it seems as shown below.  The 3 posts below do not have translations but it wants to attach id: 5834 to each of them. 

    {
        "title": {
            "rendered": "How to heat a tent during winter camping?"
        },
        "wpml_current_locale": "en_US",
        "wpml_translations": {
            "es_ES": {
                "locale": "es_ES",
                "id": 5834,
                "slug": "butano-vs-propano-cual-es-el-mejor-combustible-para-una-estufa-de-camping",
                "post_title": "Butano vs Propano – ¿Cuál es el mejor combustible para una estufa de camping?",
                "href": "https://trucampers.com/es/butano-vs-propano-cual-es-el-mejor-combustible-para-una-estufa-de-camping/"
            }
        }
    },
    {
        "title": {
            "rendered": "How To Avoid Frostbite During Winter Camping?"
        },
        "wpml_current_locale": "en_US",
        "wpml_translations": {
            "es_ES": {
                "locale": "es_ES",
                "id": 5834,
                "slug": "butano-vs-propano-cual-es-el-mejor-combustible-para-una-estufa-de-camping",
                "post_title": "Butano vs Propano – ¿Cuál es el mejor combustible para una estufa de camping?",
                "href": "https://trucampers.com/es/butano-vs-propano-cual-es-el-mejor-combustible-para-una-estufa-de-camping/"
            }
        }
    },
    {
        "title": {
            "rendered": "How to keep water from freezing during winter camping?"
        },
        "wpml_current_locale": "en_US",
        "wpml_translations": {
            "es_ES": {
                "locale": "es_ES",
                "id": 5834,
                "slug": "butano-vs-propano-cual-es-el-mejor-combustible-para-una-estufa-de-camping",
                "post_title": "Butano vs Propano – ¿Cuál es el mejor combustible para una estufa de camping?",
                "href": "https://trucampers.com/es/butano-vs-propano-cual-es-el-mejor-combustible-para-una-estufa-de-camping/"
            }
        }
    },

**Comment by shawnhooper** [comment]
Hey @jcsacto! 

Thanks for reaching out.  That's an odd bug.  When I try on my local, I see an empty array when there's no translation: 

![image](https://github.com/shawnhooper/wpml-rest-api/assets/2073284/89e10e0d-74d1-44e4-b0ad-28836d64ccd7)

I also just checked your API output, and I'm not seeing post 5834 anywhere.  Was it deleted?

**Comment by jcsacto** [comment]
Thanks for the response @shawnhooper, basically when I run this call I get a bunch of records at the end that show a Spanish translations with an ID of 5834, which is a WPML post but not the one that goes with those articles.  

https://trucampers.com/wp-json/wp/v2/posts?_fields=title,wpml_translations,wpml_current_locale&per_page=100&page=1&status=publish

**Comment by shawnhooper** [comment]
@jcsacto Is there any chance I could get a backup of your database to test this with on my end ?

**Comment by jcsacto** [comment]
@shawnhooper  I can, or I have a Dev environment I can just give you access to if that's easier?  if you do need a DB backup, let me know if you only want specific tables and where I can share that privately with you.  Thanks!

**Comment by shawnhooper** [comment]
@jcsacto A dev environment would be great. Can you add an admin user with the email GitHubHelp@shawnhooper.ca ?

**Comment by jcsacto** [comment]
@shawnhooper  invite sent, please let me know whenever you are done so I can lock the 'front door' on that site.

**Comment by shawnhooper** [comment]
@jcsacto Found the bug!   I've fixed it and uploaded v2.0.1 to the main branch here: https://github.com/shawnhooper/wpml-rest-api

**Comment by jcsacto** [comment]
@shawnhooper  apologies, but I'm not seeing any difference, I downloaded and installed version 2.0.1 to my prod site and still getting a bunch of false positive translations for post ID 5834.  I tried restarted cache on my site and in Postman also, is there something else I should do to see the fix?  Thanks once again for looking into this for me.

**Comment by shawnhooper** [comment]
@jcsacto 

When I go to: http://trucampersdev.wpengine.com/wp-json/wp/v2/posts/?per_page=100 
I see: 3 results if I search for "5834".

When I go to: http://trucampers.com/wp-json/wp/v2/posts/?per_page=100 
I see: 19 results if I search for "5834".

**Comment by jcsacto** [comment]
@shawnhooper  apologies again, it was my Postman cache, didn't realize it was so 'sticky', it's looking great now, thanks so much again!!

**Comment by jcsacto** [comment]
I'm sure it's something with my WPEngine cache then, I thought it was fixed a minute ago but was looking at the wrong response.  I will give it another hour or so to propogate hopefully because everything does look good in Dev, thanks again!

**Comment by shawnhooper** [comment]
@jcsacto Ok, I'll leave this issue open until you confirm it's working in prod.

**Comment by jcsacto** [comment]
Hi @shawnhooper , so it's not not showing in my production tenant for some reason, Dev was a clone of production so I'm baffled as to why it's not working.  Did you do anything special when you resintalled or updated the plugin in Dev that I could missing?  I tried doing update in place and a uninstall/reinstall, cleared all caches, waited overnight, etc. and it's still not working.  Sorry for the trouble here.

**Comment by shawnhooper** [comment]
@jcsacto All I did was upload the new version of the plugin.  

What happens if you re-sync production -> staging in WPE?  What's the resulting REST results in staging after that?

**Comment by shawnhooper** [comment]
@jcsacto Any luck?

**Comment by jcsacto** [comment]
@shawnhooper  so I just copied prod down to staging and and ran the GET call and it works as expected?  I'm dumbfounded at this point as it's still not working when I call it in production.  Any suggestions?  :)

**Comment by shawnhooper** [comment]
@jcsacto I've asked a friend at WPE if they have any suggestions. 

In the meantime, I'm wondering if doing the reverse, promoting staging back to production, would unstick whatever is causing this.

**Comment by jcsacto** [comment]
@shawnhooper  I tried the reverse (staging back to prod) and it's doing the same thing, but I noticed that the 2 articles I wrote last week are not showing up in prod after I pushed from staging (even though they are in staging).  So, some kind of cache is REALLY sticky in production I think and not getting the latest data, even though I keep clearing all caches in production tenant.  Will be curious what your friend says and once again, really appreciate you helping me out here!

**Comment by shawnhooper** [comment]
@jcsacto 

If I go to https://trucampers.com/wp-json/wp/v2/posts/?per_page=100 I see the 19 results that you're seeing (as if I'd never fixed the plugin) 

If I go to https://trucampers.com/wp-json/wp/v2/posts/?per_page=100&x=1 (I just added a random variable here, it could be anything) I see only the 3 results I expected. 

This leads me to believe https://trucampers.com/wp-json/wp/v2/posts/?per_page=100 is being cached.

I'd recommend you reach out to WPE support and ask about clearing the REST API cache.

**Comment by jcsacto** [comment]
@shawnhooper you are right!  I changed the per_page=99 and it returned the correct results...then changed it back to per_page=100 and it was wrong again.  So strange...CDN's I guess.  I will reach out to them, I think for now you can close this.  Thanks again!

**Comment by shawnhooper** [comment]
@jcsacto Good luck!
